### ISSUE TITLE
Feature Request: SAP Note 2718300 Integration

### ISSUE THREAD

**Issue by tbludau** [linux-system-roles/sap-netweaver-preconfigure#30]
We had a problem with a to long hostname by a customer.
It would be grate if this could be also checked in this role.

Description: 

Physical and Virtual hostname length limitations

The length of SAPLOCALHOST is up to 13 characters and the length of SAPLOCALHOSTFULL, which is the FQDN can be longer than 13 characters. So basically:

It is acceptable to use a longer (e.g. 15 character) physical hostname for hosts running non-Netweaver services like HANA, SAPRouter, Data Services, BOBJ, SAP Web Dispatcher. (see Note 2074402)
A virtual hostname is not required for the systems listed in Point 1 above.
For all hosts running Netweaver, a physical hostname may be longer than 13 characters as long as there is:
 a virtual hostname (i.e. SAPLOCALHOST) defined that is 13 characters or less and
 the shorter virtual hostname is always the one referenced within SAP. (See Note 962955)

**Comment by berndfinger** [comment]
Does https://github.com/linux-system-roles/sap-preconfigure/issues/119 cover this issue?

**Comment by berndfinger** [comment]
I assume yes, so I am closing this issue now.
